homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_installed_packages:
  - python2
  - python3
  - dockutil
  - tmux
  - jq
  - wget
  - gpg
  - packer
  - vault
  - terraform

homebrew_cask_apps:
  - alfred
  - iterm2
  - google-chrome
  - omnifocus
  - fantastical
  - 1password
  - 1password-cli
  - bartender
  - toggl
  - logos
  - docker
  - firefox
  - aws-vault
  - vlc
  - calibre
  - duet
  - ubersicht
  - dash
  - odrive
  - java
  - handbrake
  - vagrant
  - intellij-idea
  - google-cloud-sdk
  - keybase
  - parallels
  - ykman

mas_installed_apps:
  - { id: 975937182, name: "Fantastical 2" }
  - { id: 803453959, name: "Slack" }
  - { id: 1176895641, name: "Spark" }
  - { id: 1091189122, name: "Bear"}
  - { id: 451907568, name: "Paprika Recipe Manager" }
  - { id: 407963104, name: "Pixelmator" }
  - { id: 715768417, name: "Microsoft Remote Desktop" }
  - { id: 905384638, name: "Filebot" }
  - { id: 441258766, name: "Magnet" }
  - { id: 405399194, name: "Kindle" }
  - { id: 1094748271, name: "Full Contact" }
  - { id: 572491815, name: "Textastic" }
  - { id: 1437130425, name: "Jolt of Caffiene" }
  - { id: 497799835, name: "Xcode" }
  - { id: 1055511498, name: "Day One" }

pip_items:
  - virtualenvwrapper

gem_items:
  - tmuxinator

dockitems_to_remove:
  - Siri
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iBooks
  - Calendar
  - News

dockitems_to_persist:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 2
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 3
  - name: OmniFocus
    path: "/Applications/OmniFocus.app"
    pos: 4
  - name: Fantastical 2
    path: "/Applications/Fantastical 2.app"
    pos: 5
  - name: Messages
    path: /Applications/Messages.app
    pos: 6
  - name: iTunes
    path: /Applications/iTunes.app
    pos: 7
  - name: App Store
    path: "/Applications/App Store.app"
    pos: 8
  - name: System Preferences
    path: "/Applications/System Preferences.app"
    pos: 9
