homebrew_taps:
  - versent/homebrew-taps
  - aws/tap
  - hashicorp/tap 

homebrew_installed_packages:
  - python3
  - virtualenvwrapper
  - dockutil
  - gpg
  - pinentry-mac
  - mas
  - tmux
  - awscli
  - wget
  - jq
  - tflint
  - vault
  - packer
  - tfenv
  - terraform-docs
  - pre-commit
  - gawk
  - cfn-lint
  - aws-sam-cli
  - ffmpeg
  - mp4v2
  - mp3val
  - mp3splt
  - rbenv
  - openjdk
  - node
  - go
  - groovy
  - checkov

homebrew_cask_apps:
  - alfred
  - iterm2
  - 1password
  - omnifocus
  - devonthink
  - obsidian
  - textexpander
  - keyboard-maestro
  - elgato-stream-deck
  - visual-studio-code
  - keybase
  - calibre
  - vlc
  - nordvpn
  - logitech-options
  - sf-symbols
  - microsoft-office
  - google-chrome
  - firefox
  - zoom
  - docker
  - 1password-cli
  - hookmark
  - logos
  - freedom
  - scrivener
  - setapp

mas_installed_apps:
  - { id: 441258766, name: "Magnet" }
  - { id: 1425368544, name: "Timery" }
  - { id: 1435957248, name: "Drafts" }
  - { id: 975937182, name: "Fantastical 2" }
  - { id: 803453959, name: "Slack" }
  - { id: 1295203466, name: "Remote Desktop 10" }
  - { id: 1529448980, name: "Reeder 5" }
  - { id: 572491815, name: "Textastic" }
  - { id: 419330170, Name: "Moom" }
  - { id: 1354318707, name: "Core Tunnel" }
  - { id: 1444383602, name: "GoodNotes" }
  - { id: 1290358394, name: "Cardhop" }
  - { id: 1055511498, name: "Day One" }
  - { id: 497799835, name: "XCode" }
  - { id: 672401817, Name: "Strides" }

pip_items: []

gem_items: []

npm_items: []
  

dockitems_to_remove:
  - Siri
  - Mail
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iBooks
  - Calendar
  - News
  - Podcasts
  - TV
  - Safari

dockitems_to_persist:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Safari
    path: "/Applications/Safari.app"
    pos: 2
  - name: iTerm
    path: "/Applications/iTerm.app"
    pos: 3
  - name: Drafts
    path: "/Applications/Drafts.app"
    pos: 4
  - name: Obsidian
    path: "/Applications/Obsidian.app"
    pos: 5
  - name: OmniFocus
    path: "/Applications/OmniFocus.app"
    pos: 6
  - name: Messages
    path: "/System/Applications/Messages.app"
    pos: 7
  - name: Music
    path: "/System/Applications/Music.app"
    pos: 8
  - name: App Store
    path: "/Applications/App Store.app"
    pos: 9
  - name: System Settings
    path: "/System/Applications/System Settings.app"
    pos: 10

#wallpaper_file: cross.jpg
