homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - versent/homebrew-taps

homebrew_installed_packages:
  - python2
  - python3
  - node
  - rbenv
  - dockutil
  - wget
  - gpg
  - pinentry-mac
  - tmux
  - jq
  - saml2aws
  - awscli

homebrew_cask_apps:
  - firefox
  - alfred
  - iterm2
  - bartender
  - 1password
  - 1password-cli
  - microsoft-office
  - setapp
  - boxcryptor
  - freedom
  - keybase
  - textexpander
  - keyboard-maestro
  - toggl
  - docker
  - vlc
  - duet
  - ubersicht
  - java
  - intellij-idea
  - pycharm
  - clion
  - send-to-kindle
  - calibre
  - google-chrome
  - logos
  - vagrant
  - omnioutliner
  - omnifocus
  - dash
  - vmware-fusion
  - zoom

mas_installed_apps:
  - { id: 441258766, name: "Magnet" }
  - { id: 975937182, name: "Fantastical 2" }
  - { id: 1091189122, name: "Bear"}
  - { id: 572491815, name: "Textastic" }
  - { id: 803453959, name: "Slack" }
  - { id: 1055511498, name: "Day One" }
  - { id: 1369500258, name: "Anesidora" }
  - { id: 777233759, name: "Focus - Time Manager" }
  - { id: 1295203466, name: "Remote Desktop 10" }
  - { id: 412946682, name: "SubnetCalc" }
  - { id: 497799835, name: "Xcode" }

pip_items:
  - virtualenvwrapper

gem_items: []

npm_items:
  - serverless

dockitems_to_remove:
  - Siri
  - Mail
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iBooks
  - Calendar
  - News
  - Podcasts
  - TV
  - Safari

dockitems_to_persist:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Firefox
    path: /Applications/Firefox.app
    pos: 2
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 3
  - name: OmniFocus
    path: "/Applications/OmniFocus.app"
    pos: 4
  - name: Messages
    path: /System/Applications/Messages.app
    pos: 5
  - name: Music
    path: /System/Applications/Music.app
    pos: 6
  - name: App Store
    path: "/Applications/App Store.app"
    pos: 7
  - name: System Preferences
    path: "/Applications/System Preferences.app"
    pos: 8

wallpaper_file: janky.jpg
