homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_installed_packages:
  - python3
  - dockutil

homebrew_cask_apps:
  - alfred
  - iterm2
  - 1password
  - omnifocus

mas_installed_apps:
  - { id: 441258766, name: "Magnet" }

pip_items:
  - virtualenvwrapper

gem_items: []

npm_items: []
  

dockitems_to_remove:
  - Siri
  - Mail
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iBooks
  - Calendar
  - News
  - Podcasts
  - TV
  - Safari

dockitems_to_persist:
  - name: Launchpad
    path: "/Applications/Launchpad.app"
    pos: 1
  - name: Safari
    path: /Applications/Safari.app
    pos: 2
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 3
  - name: OmniFocus
    path: "/Applications/OmniFocus.app"
    pos: 4
  - name: Messages
    path: /System/Applications/Messages.app
    pos: 5
  - name: Music
    path: /System/Applications/Music.app
    pos: 6
  - name: App Store
    path: "/Applications/App Store.app"
    pos: 7
  - name: System Preferences
    path: "/Applications/System Preferences.app"
    pos: 8

wallpaper_file: cross.jpg
